// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

[PrimaryKey("LojaId", "ProdutoId")]
[Table("ItemEstoque")]
public partial class ItemEstoque
{
    [Key]
    public int LojaId { get; set; }

    [Key]
    public int ProdutoId { get; set; }

    public int Quantidade { get; set; }

    [ForeignKey("LojaId")]
    [InverseProperty("ItemEstoques")]
    public virtual Loja Loja { get; set; }

    [ForeignKey("ProdutoId")]
    [InverseProperty("ItemEstoques")]
    public virtual Produto Produto { get; set; }
}