// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public partial class Loja
{
    [Key]
    public int LojaId { get; set; }

    [Required]
    [StringLength(100)]
    public string Nome { get; set; }

    [Required]
    [StringLength(250)]
    public string Endereco { get; set; }

    [StringLength(15)]
    public string Telefone { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    [InverseProperty("Loja")]
    public virtual ICollection<ItemEstoque> ItemEstoques { get; set; } = new List<ItemEstoque>();
}