// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public partial class Produto
{
    [Key]
    public int ProdutoId { get; set; }

    [Required]
    [StringLength(100)]
    public string Nome { get; set; }

    [StringLength(500)]
    public string Descricao { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ValorCompra { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? ValorVenda { get; set; }

    public byte[]? Imagem { get; set; }

    [InverseProperty("Produto")]
    public virtual ICollection<ItemEstoque> ItemEstoques { get; set; } = new List<ItemEstoque>();
}