// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

[Table("StockItem")]
public partial class StockItem
{
    [Key]
    public int StockId { get; set; }

    public int StockProductId { get; set; }

    public int StockStoreId { get; set; }

    [Column("QTY")]
    public int QTY { get; set; }

    [ForeignKey("StockProductId")]
    [InverseProperty("StockItems")]
    public virtual Product StockProduct { get; set; }

    [ForeignKey("StockStoreId")]
    [InverseProperty("StockItems")]
    public virtual Store StockStore { get; set; }
}