// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public partial class Store
{
    [Key]
    public int StoreId { get; set; }

    public string UserId { get; set; }

    [Required]
    [StringLength(100)]
    [Display(Name = "Nome da loja")]
    public string StoreName { get; set; }

    [Required]
    [StringLength(8)]
    [Display(Name = "CEP (Apenas números)")]
    public string CEP { get; set; }


    [Display(Name = "Cidade")]
    public string? City { get; set; }


    [Display(Name = "Bairro")]
    public string? Neighborhood { get; set; }

    [Display(Name = "Rua")]
    public string? Adress { get; set; }

    [StringLength(15)]
    [Display(Name = "Telefone")]
    public string Phone { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    [InverseProperty("StockStore")]
    public virtual ICollection<StockItem> StockItems { get; set; } = new List<StockItem>();
}