// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public partial class Store
{
    [Key]
    public int StoreId { get; set; }

    [Required]
    [StringLength(100)]
    [Display(Name = "Nome da loja")]
    public string StoreName { get; set; }

    [Required]
    [StringLength(250)]
    [Display(Name = "CEP")]
    public string Adress { get; set; }

    [StringLength(15)]
    [Display(Name = "Telefone")]
    public string Phone { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    [InverseProperty("StockStore")]
    public virtual ICollection<StockItem> StockItems { get; set; } = new List<StockItem>();
}